//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDD_GV
    {
        public int MaDD { get; set; }
        public int MaGV { get; set; }
        public Nullable<System.TimeSpan> ThoiGianVao { get; set; }
        public Nullable<System.TimeSpan> ThoiGianRa { get; set; }
        public Nullable<bool> TTDD { get; set; }
    
        public virtual DIEMDANH DIEMDANH { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
    }
}
