//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH_GV
    {
        public int MaHA { get; set; }
        public string TenHA { get; set; }
        public string BASE64 { get; set; }
        public Nullable<int> MaGV { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
    }
}
