//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHGIANGDAY
    {
        public int MaNMH { get; set; }
        public Nullable<bool> ThuHai { get; set; }
        public Nullable<bool> ThuBa { get; set; }
        public Nullable<bool> ThuTu { get; set; }
        public Nullable<bool> ThuNam { get; set; }
        public Nullable<bool> ThuSau { get; set; }
        public Nullable<bool> ThuBay { get; set; }
    
        public virtual NHOMMONHOC NHOMMONHOC { get; set; }
    }
}
