//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMMONHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOMMONHOC()
        {
            this.DIEMDANHs = new HashSet<DIEMDANH>();
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public int MaNMH { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<int> MaPhongHoc { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBD { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMDANH> DIEMDANHs { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual LICHGIANGDAY LICHGIANGDAY { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
